version: 2

project_name: AetherOneGo

builds:
  - id: aetheronego
    main: ./go/main.go
    binary: AetherOneGo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: ['tar.gz', 'zip']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      formats: ["zip"]

nfpms:
  - maintainer: Isuret Polos <isuret.polos@gmail.com>
    description: AetherOneGo
    homepage: https://www.patreon.com/c/aetherone
    license: MIT
    formats:
      - deb
      - rpm
      - apk
